ALTER TABLE `clan` ADD COLUMN `founder` BIGINT(20) UNSIGNED NOT NULL AFTER `foundTime`;
ALTER TABLE `clan_player` DROP COLUMN `donateSkill`,  DROP COLUMN `donateType`,  DROP COLUMN `donateCount`,  DROP COLUMN `donateTime`;
UPDATE `clan` AS `update_clan`  SET  `founder` = (SELECT `playerId` FROM `clan_player`  WHERE  `id` = `update_clan`.`id`  ORDER BY `joinTime`  limit 1);
CREATE TABLE `clan_donate_record` (`clanId` INT(10) UNSIGNED NOT NULL, `donateName` VARCHAR(255) NOT NULL DEFAULT '', `skillId` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0', `donateCount` INT(10) UNSIGNED NOT NULL DEFAULT '0', `donateTime` INT(10) UNSIGNED NOT NULL DEFAULT '0') COLLATE='utf8_general_ci' ENGINE=InnoDB ROW_FORMAT=DEFAULT;
INSERT INTO `clan_skill` SELECT `id`, 3, 0, 0 FROM `clan`;
INSERT INTO `clan_skill` SELECT `id`, 4, 0, 0 FROM `clan`;
INSERT INTO `clan_skill` SELECT `id`, 5, 0, 0 FROM `clan`;
INSERT INTO `clan_skill` SELECT `id`, 6, 0, 0 FROM `clan`;
INSERT INTO `clan_skill` SELECT `id`, 7, 0, 0 FROM `clan`;
INSERT INTO `clan_skill` SELECT `id`, 8, 0, 0 FROM `clan`;
INSERT INTO `clan_skill` SELECT `id`, 9, 0, 0 FROM `clan`;
ALTER TABLE `boss` ADD COLUMN `level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `id`;
