ALTER TABLE `clan` ADD COLUMN `enemyClan1` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `allyClan`, ADD COLUMN `enemyClan2` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `enemyClan1`, ADD COLUMN `hasBattle` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `hallEdurance`;
CREATE TABLE `clan_battle_result` (`id` INT(10) UNSIGNED NOT NULL, `battleTime` INT(10) UNSIGNED NOT NULL, `result` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0', PRIMARY KEY (`id`, `battleTime`)) COLLATE='utf8_general_ci' ENGINE=InnoDB ROW_FORMAT=DEFAULT;
DELETE FROM `clan_battler`;
ALTER TABLE `clan_battler` ADD COLUMN `id` INT(10) UNSIGNED NOT NULL FIRST, ADD COLUMN `battlerLev` INT(10) UNSIGNED NOT NULL AFTER `battler`, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`);
