CREATE TABLE `tavern` (
	`country` TINYINT(1) UNSIGNED NOT NULL,
	`id` TINYINT(3) UNSIGNED NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`class` TINYINT(1) UNSIGNED NOT NULL,
	`potential` FLOAT(5,2) UNSIGNED NOT NULL,
	`portrait` TINYINT(3) UNSIGNED NOT NULL,
	`bidder` BIGINT(20) UNSIGNED NOT NULL,
	`price` INT(10) UNSIGNED NOT NULL,
	`bidCount` SMALLINT(5) UNSIGNED NOT NULL,
	UNIQUE INDEX `country_id` (`country`, `id`)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;
