CREATE TABLE `auto_battle` (
	`playerId` BIGINT(20) UNSIGNED NOT NULL,
	`npcId` INT(10) UNSIGNED NOT NULL,
	`count` MEDIUMINT(5) UNSIGNED NOT NULL,
	`interval` MEDIUMINT(5) UNSIGNED NOT NULL,
	PRIMARY KEY (`playerId`)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
CHARSET=utf8;