ALTER TABLE `clan` ADD COLUMN `proffer` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `battleTime` TINYINT(3) UNSIGNED NOT NULL DEFAULT '16',
	ADD COLUMN `nextBattleTime` TINYINT(3) UNSIGNED NOT NULL DEFAULT '16',
	ADD COLUMN `favorId1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `favorId2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `favorId3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `favorId4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `favorTime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `allyClan1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `allyClan2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `allyClan3` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	ADD COLUMN `battleStartTime` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '战斗开启时间，用于服务器重启用',
	ADD COLUMN `battleStatus` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '战斗状态',
	ADD COLUMN `southEdurance` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '30',
	ADD COLUMN `northEdurance` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '30',
	ADD COLUMN `hallEdurance` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '30';

DELETE FROM `clan_player` WHERE `class` = 16;

ALTER TABLE `clan_player` DROP COLUMN `class`, DROP COLUMN `advReg`,
	ADD COLUMN `battleClanId` INT(10) UNSIGNED NOT NULL,
	ADD COLUMN `battleClanTime` INT(10) UNSIGNED NOT NULL COMMENT '此宗族战开放时间',
	ADD COLUMN `battleClanHold` SMALLINT(5) UNSIGNED NOT NULL,
	CHANGE COLUMN `optime` `joinTime` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '成员 - 加入时间    待审核 - 申请时间' AFTER `battleClanHold`,
	ADD COLUMN `proffer` INT(10) UNSIGNED NOT NULL,
	ADD COLUMN `enterCount` TINYINT(3) UNSIGNED NOT NULL,
	ADD COLUMN `donateSkill` TINYINT(3) UNSIGNED NOT NULL,
	ADD COLUMN `donateType` SMALLINT(5) UNSIGNED NOT NULL COMMENT '1：宗族等级\\r\\n2：宗族经验\\r\\nID：喜好品',
	ADD COLUMN `donateCount` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `donateTime` INT(10) UNSIGNED NOT NULL,
	ADD COLUMN `achieveCount` SMALLINT(5) UNSIGNED NOT NULL COMMENT '前当累计捐献战功',
	ADD COLUMN `achieveTime` INT(10) UNSIGNED NOT NULL COMMENT '后最捐献时间',
	ADD COLUMN `taelCount` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `taelTime` INT(10) UNSIGNED NOT NULL,
	ADD COLUMN `petFriendness1` SMALLINT(5) UNSIGNED NOT NULL COMMENT '青龙的亲密值',
	ADD COLUMN `petFriendness2` SMALLINT(5) UNSIGNED NOT NULL COMMENT '白虎的亲密值',
	ADD COLUMN `petFriendness3` SMALLINT(5) UNSIGNED NOT NULL COMMENT '朱雀的亲密值',
	ADD COLUMN `petFriendness4` SMALLINT(5) UNSIGNED NOT NULL COMMENT '玄武的亲密值',
	ADD COLUMN `favorCount1` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `lastFavorTime1` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `favorCount2` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `lastFavorTime2` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `favorCount3` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `lastFavorTime3` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `favorCount4` SMALLINT(5) UNSIGNED NOT NULL,
	ADD COLUMN `lastFavorTime4` SMALLINT(5) UNSIGNED NOT NULL;

CREATE TABLE `clan_battler` (
	`battler` BIGINT(20) UNSIGNED NOT NULL,
	`battleClanId` INT(10) UNSIGNED NOT NULL,
	`battleClanTime` INT(10) UNSIGNED NOT NULL,
	`battleHold` INT(10) UNSIGNED NOT NULL,
	`reliveNum` SMALLINT(5) UNSIGNED NOT NULL,
	`wins` SMALLINT(5) UNSIGNED NOT NULL,
	`serialWins` SMALLINT(5) UNSIGNED NOT NULL,
	`southEdurance` SMALLINT(5) UNSIGNED NOT NULL,
	`northEdurance` SMALLINT(5) UNSIGNED NOT NULL,
	`grabAchieve` SMALLINT(5) UNSIGNED NOT NULL,
	`enterCount` TINYINT(3) UNSIGNED NOT NULL,
	`hasEnter` TINYINT(3) UNSIGNED NOT NULL,
	`flag` TINYINT(3) UNSIGNED NOT NULL,
	PRIMARY KEY (`battler`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;

CREATE TABLE `clan_pet_friendliness` (
	`memberId` BIGINT(20) UNSIGNED NOT NULL,
	`clanId` INT(10) UNSIGNED NOT NULL,
	`petId` SMALLINT(5) UNSIGNED NOT NULL,
	`friendliness` INT(10) UNSIGNED NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;

CREATE TABLE `clan_skill` (
	`clanId` INT(10) UNSIGNED NOT NULL,
	`skillId` SMALLINT(5) UNSIGNED NOT NULL,
	`level` SMALLINT(5) UNSIGNED NOT NULL,
	`extra` INT(11) NOT NULL,
	PRIMARY KEY (`clanId`, `skillId`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;

CREATE TABLE `clan_pending_player` (
	`id` INT(10) UNSIGNED NOT NULL,
	`playerId` BIGINT(20) UNSIGNED NOT NULL,
	`class` TINYINT(3) UNSIGNED NOT NULL,
	`opTime` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`, `playerId`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT;
