CREATE TABLE `arena_bet` (
	`id` BIGINT(20) UNSIGNED NOT NULL,
	`round` TINYINT(3) UNSIGNED NOT NULL,
	`group` TINYINT(3) UNSIGNED NOT NULL,
	`pos` TINYINT(3) UNSIGNED NOT NULL,
	`tael` TINYINT(3) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`, `round`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;