-- *************宝具名字配置*************
-- 1.未通灵宝具item：
-- 【level】 - 等级 70、80、90、100 【color】颜色 ◆1（绿色） ◆2（蓝色） ◆3（紫色） ◆4（橙色）【type】 - 类型 ◆1（灵） ◆2（悟） ◆3（信）【name】 - 未通灵宝具的名字前缀
-- 2.通灵宝具前缀item2：
-- 【leµ抗） ◆11（身法） ◆12（生命） 【name】
-- 通灵宝具的名字前缀 
-- 3.通灵宝具后缀item3： 【level】- 等级（同上） 【type】 - 类型（同上） 【name】 - 宝具的名字后缀
lbnametmpl:setColorPrefix(70, 1, 1, "朴素的")
lbnametmpl:setColorPrefix(70, 2, 1, "精致的")
lbnametmpl:setColorPrefix(70, 3, 1, "华丽的")
lbnametmpl:setColorPrefix(70, 4, 1, "神秘的")

lbnametmpl:setColorPrefix(70, 1, 2, "破旧的")
lbnametmpl:setColorPrefix(70, 2, 2, "别致的")
lbnametmpl:setColorPrefix(70, 3, 2, "罕见的")
lbnametmpl:setColorPrefix(70, 4, 2, "神奇的")

lbnametmpl:setColorPrefix(70, 1, 3, "破损的")
lbnametmpl:setColorPrefix(70, 2, 3, "坚固的")
lbnametmpl:setColorPrefix(70, 3, 3, "特制的")
lbnametmpl:setColorPrefix(70, 4, 3, "神佑的")

lbnametmpl:setColorPrefix(80, 1, 1, "朴素的")
lbnametmpl:setColorPrefix(80, 2, 1, "精致的")
lbnametmpl:setColorPrefix(80, 3, 1, "华丽的")
lbnametmpl:setColorPrefix(80, 4, 1, "神秘的")

lbnametmpl:setColorPrefix(80, 1, 2, "破旧的")
lbnametmpl:setColorPrefix(80, 2, 2, "别致的")
lbnametmpl:setColorPrefix(80, 3, 2, "罕见的")
lbnametmpl:setColorPrefix(80, 4, 2, "神奇的")

lbnametmpl:setColorPrefix(80, 1, 3, "破损的")
lbnametmpl:setColorPrefix(80, 2, 3, "坚固的")
lbnametmpl:setColorPrefix(80, 3, 3, "特制的")
lbnametmpl:setColorPrefix(80, 4, 3, "神佑的")

lbnametmpl:setColorPrefix(90, 1, 1, "朴素的")
lbnametmpl:setColorPrefix(90, 2, 1, "精致的")
lbnametmpl:setColorPrefix(90, 3, 1, "华丽的")
lbnametmpl:setColorPrefix(90, 4, 1, "神秘的")

lbnametmpl:setColorPrefix(90, 1, 2, "破旧的")
lbnametmpl:setColorPrefix(90, 2, 2, "别致的")
lbnametmpl:setColorPrefix(90, 3, 2, "罕见的")
lbnametmpl:setColorPrefix(90, 4, 2, "神奇的")

lbnametmpl:setColorPrefix(90, 1, 3, "破损的")
lbnametmpl:setColorPrefix(90, 2, 3, "坚固的")
lbnametmpl:setColorPrefix(90, 3, 3, "特制的")
lbnametmpl:setColorPrefix(90, 4, 3, "神佑的")

lbnametmpl:setColorPrefix(100, 1, 1, "朴素的")
lbnametmpl:setColorPrefix(100, 2, 1, "精致的")
lbnametmpl:setColorPrefix(100, 3, 1, "华丽的")
lbnametmpl:setColorPrefix(100, 4, 1, "神秘的")

lbnametmpl:setColorPrefix(100, 1, 2, "破旧的")
lbnametmpl:setColorPrefix(100, 2, 2, "别致的")
lbnametmpl:setColorPrefix(100, 3, 2, "罕见的")
lbnametmpl:setColorPrefix(100, 4, 2, "神奇的")

lbnametmpl:setColorPrefix(100, 1, 3, "破损的")
lbnametmpl:setColorPrefix(100, 2, 3, "坚固的")
lbnametmpl:setColorPrefix(100, 3, 3, "特制的")
lbnametmpl:setColorPrefix(100, 4, 3, "神佑的")

lbnametmpl:setAttrPrefix(70, 1, "夺命之")
lbnametmpl:setAttrPrefix(70, 2, "御敌之")
lbnametmpl:setAttrPrefix(70, 3, "豪火之")
lbnametmpl:setAttrPrefix(70, 4, "驱神之")
lbnametmpl:setAttrPrefix(70, 5, "猛虎之")
lbnametmpl:setAttrPrefix(70, 6, "溶甲之")
lbnametmpl:setAttrPrefix(70, 7, "灵猴之")
lbnametmpl:setAttrPrefix(70, 8, "猎鹰之")
lbnametmpl:setAttrPrefix(70, 9, "泰山之")
lbnametmpl:setAttrPrefix(70, 10, "冰心之")
lbnametmpl:setAttrPrefix(70, 11, "迅豹之")
lbnametmpl:setAttrPrefix(70, 12, "长生之")

lbnametmpl:setAttrPrefix(80, 1, "夺命之")
lbnametmpl:setAttrPrefix(80, 2, "御敌之")
lbnametmpl:setAttrPrefix(80, 3, "豪火之")
lbnametmpl:setAttrPrefix(80, 4, "驱神之")
lbnametmpl:setAttrPrefix(80, 5, "猛虎之")
lbnametmpl:setAttrPrefix(80, 6, "溶甲之")
lbnametmpl:setAttrPrefix(80, 7, "灵猴之")
lbnametmpl:setAttrPrefix(80, 8, "猎鹰之")
lbnametmpl:setAttrPrefix(80, 9, "泰山之")
lbnametmpl:setAttrPrefix(80, 10, "冰心之")
lbnametmpl:setAttrPrefix(80, 11, "迅豹之")
lbnametmpl:setAttrPrefix(80, 12, "长生之")

lbnametmpl:setAttrPrefix(90, 1, "夺命之")
lbnametmpl:setAttrPrefix(90, 2, "御敌之")
lbnametmpl:setAttrPrefix(90, 3, "豪火之")
lbnametmpl:setAttrPrefix(90, 4, "驱神之")
lbnametmpl:setAttrPrefix(90, 5, "猛虎之")
lbnametmpl:setAttrPrefix(90, 6, "溶甲之")
lbnametmpl:setAttrPrefix(90, 7, "灵猴之")
lbnametmpl:setAttrPrefix(90, 8, "猎鹰之")
lbnametmpl:setAttrPrefix(90, 9, "泰山之")
lbnametmpl:setAttrPrefix(90, 10, "冰心之")
lbnametmpl:setAttrPrefix(90, 11, "迅豹之")
lbnametmpl:setAttrPrefix(90, 12, "长生之")

lbnametmpl:setAttrPrefix(100, 1, "夺命之")
lbnametmpl:setAttrPrefix(100, 2, "御敌之")
lbnametmpl:setAttrPrefix(100, 3, "豪火之")
lbnametmpl:setAttrPrefix(100, 4, "驱神之")
lbnametmpl:setAttrPrefix(100, 5, "猛虎之")
lbnametmpl:setAttrPrefix(100, 6, "溶甲之")
lbnametmpl:setAttrPrefix(100, 7, "灵猴之")
lbnametmpl:setAttrPrefix(100, 8, "猎鹰之")
lbnametmpl:setAttrPrefix(100, 9, "泰山之")
lbnametmpl:setAttrPrefix(100, 10, "冰心之")
lbnametmpl:setAttrPrefix(100, 11, "迅豹之")
lbnametmpl:setAttrPrefix(100, 12, "长生之")

lbnametmpl:setLBName(70, 1, "剑鞘")
lbnametmpl:setLBName(70, 2, "伞")
lbnametmpl:setLBName(70, 3, "镯")

lbnametmpl:setLBName(80, 1, "剑鞘")
lbnametmpl:setLBName(80, 2, "镜")
lbnametmpl:setLBName(80, 3, "链")

lbnametmpl:setLBName(90, 1, "剑匣")
lbnametmpl:setLBName(90, 2, "葫芦")
lbnametmpl:setLBName(90, 3, "护腕")

lbnametmpl:setLBName(100, 1, "剑匣")
lbnametmpl:setLBName(100, 2, "轮")
lbnametmpl:setLBName(100, 3, "水晶")

lbnametmpl:setSkillPrevfix(1, "赤尊·达摩老祖之")
lbnametmpl:setSkillPrevfix(2, "地尊·达摩老祖之")
lbnametmpl:setSkillPrevfix(3, "玄尊·达摩老祖之")
lbnametmpl:setSkillPrevfix(4, "天尊·达摩老祖之")
lbnametmpl:setSkillPrevfix(5, "赤尊·屠龙师太之")
lbnametmpl:setSkillPrevfix(6, "地尊·屠龙师太之")
lbnametmpl:setSkillPrevfix(7, "玄尊·屠龙师太之")
lbnametmpl:setSkillPrevfix(8, "天尊·屠龙师太之")
lbnametmpl:setSkillPrevfix(9, "赤尊·顽石大师之")
lbnametmpl:setSkillPrevfix(10, "地尊·顽石大师之")
lbnametmpl:setSkillPrevfix(11, "玄尊·顽石大师之")
lbnametmpl:setSkillPrevfix(12, "天尊·顽石大师之")
lbnametmpl:setSkillPrevfix(13, "赤尊·妙一真人之")
lbnametmpl:setSkillPrevfix(14, "地尊·妙一真人之")
lbnametmpl:setSkillPrevfix(15, "玄尊·妙一真人之")
lbnametmpl:setSkillPrevfix(16, "天尊·妙一真人之")
lbnametmpl:setSkillPrevfix(17, "赤尊·太元真人之")
lbnametmpl:setSkillPrevfix(18, "地尊·太元真人之")
lbnametmpl:setSkillPrevfix(19, "玄尊·太元真人之")
lbnametmpl:setSkillPrevfix(20, "天尊·太元真人之")
lbnametmpl:setSkillPrevfix(21, "赤尊·无量剑宗之")
lbnametmpl:setSkillPrevfix(22, "地尊·无量剑宗之")
lbnametmpl:setSkillPrevfix(23, "玄尊·无量剑宗之")
lbnametmpl:setSkillPrevfix(24, "天尊·无量剑宗之")
lbnametmpl:setSkillPrevfix(25, "赤尊·无尘罗汉之")
lbnametmpl:setSkillPrevfix(26, "地尊·无尘罗汉之")
lbnametmpl:setSkillPrevfix(27, "玄尊·无尘罗汉之")
lbnametmpl:setSkillPrevfix(28, "天尊·无尘罗汉之")
lbnametmpl:setSkillPrevfix(29, "赤尊·玉清大师之")
lbnametmpl:setSkillPrevfix(30, "地尊·玉清大师之")
lbnametmpl:setSkillPrevfix(31, "玄尊·玉清大师之")
lbnametmpl:setSkillPrevfix(32, "天尊·玉清大师之")
lbnametmpl:setSkillPrevfix(33, "赤尊·大智禅师之")
lbnametmpl:setSkillPrevfix(34, "地尊·大智禅师之")
lbnametmpl:setSkillPrevfix(35, "玄尊·大智禅师之")
lbnametmpl:setSkillPrevfix(36, "天尊·大智禅师之")
lbnametmpl:setSkillPrevfix(37, "赤尊·碎影剑痴之")
lbnametmpl:setSkillPrevfix(38, "地尊·碎影剑痴之")
lbnametmpl:setSkillPrevfix(39, "玄尊·碎影剑痴之")
lbnametmpl:setSkillPrevfix(40, "天尊·碎影剑痴之")
lbnametmpl:setSkillPrevfix(41, "赤尊·追命鬼差之")
lbnametmpl:setSkillPrevfix(42, "地尊·追命鬼差之")
lbnametmpl:setSkillPrevfix(43, "玄尊·追命鬼差之")
lbnametmpl:setSkillPrevfix(44, "天尊·追命鬼差之")
lbnametmpl:setSkillPrevfix(45, "赤尊·墨龙剑阵之")
lbnametmpl:setSkillPrevfix(46, "地尊·墨龙剑阵之")
lbnametmpl:setSkillPrevfix(47, "玄尊·墨龙剑阵之")
lbnametmpl:setSkillPrevfix(48, "天尊·墨龙剑阵之")
lbnametmpl:setSkillPrevfix(49, "赤尊·非攻护法之")
lbnametmpl:setSkillPrevfix(50, "地尊·非攻护法之")
lbnametmpl:setSkillPrevfix(51, "玄尊·非攻护法之")
lbnametmpl:setSkillPrevfix(52, "天尊·非攻护法之")
lbnametmpl:setSkillPrevfix(53, "地尊·驭心天皇之")
lbnametmpl:setSkillPrevfix(54, "玄尊·驭心天皇之")
lbnametmpl:setSkillPrevfix(55, "天尊·驭心天皇之")
lbnametmpl:setSkillPrevfix(56, "地尊·九转剑仙之")
lbnametmpl:setSkillPrevfix(57, "玄尊·九转剑仙之")
lbnametmpl:setSkillPrevfix(58, "天尊·九转剑仙之")
lbnametmpl:setSkillPrevfix(59, "地尊·白眉禅师之")
lbnametmpl:setSkillPrevfix(60, "玄尊·白眉禅师之")
lbnametmpl:setSkillPrevfix(61, "天尊·白眉禅师之")
lbnametmpl:setSkillPrevfix(62, "地尊·九天凤女之")
lbnametmpl:setSkillPrevfix(63, "玄尊·九天凤女之")
lbnametmpl:setSkillPrevfix(64, "天尊·九天凤女之")
lbnametmpl:setSkillPrevfix(65, "玄尊·太元祖师之")
lbnametmpl:setSkillPrevfix(66, "天尊·太元祖师之")
lbnametmpl:setSkillPrevfix(67, "玄尊·醉道人之")
lbnametmpl:setSkillPrevfix(68, "天尊·醉道人之")
lbnametmpl:setSkillPrevfix(69, "玄尊·天蒙禅师之")
lbnametmpl:setSkillPrevfix(70, "天尊·天蒙禅师之")
lbnametmpl:setSkillPrevfix(71, "玄尊·噬血剑狂之")
lbnametmpl:setSkillPrevfix(72, "天尊·噬血剑狂之")
lbnametmpl:setSkillPrevfix(73, "天尊·万影剑圣之")

lbnametmpl:setSkillSuffix(74, "刚毅")
lbnametmpl:setSkillSuffix(75, "刚毅")
lbnametmpl:setSkillSuffix(76, "刚毅")
lbnametmpl:setSkillSuffix(77, "刚毅")
lbnametmpl:setSkillSuffix(78, "奇袭")
lbnametmpl:setSkillSuffix(79, "奇袭")
lbnametmpl:setSkillSuffix(80, "奇袭")
lbnametmpl:setSkillSuffix(81, "奇袭")
lbnametmpl:setSkillSuffix(82, "猛进")
lbnametmpl:setSkillSuffix(83, "猛进")
lbnametmpl:setSkillSuffix(84, "猛进")
lbnametmpl:setSkillSuffix(85, "强袭")
lbnametmpl:setSkillSuffix(86, "强袭")
lbnametmpl:setSkillSuffix(87, "强袭")
lbnametmpl:setSkillSuffix(88, "狂骨")
lbnametmpl:setSkillSuffix(89, "狂骨")
lbnametmpl:setSkillSuffix(90, "无双")
lbnametmpl:setSkillSuffix(91, "无双")
lbnametmpl:setSkillSuffix(92, "龙胆")
lbnametmpl:setSkillSuffix(93, "咆哮")
lbnametmpl:setSkillSuffix(94, "不屈")
lbnametmpl:setSkillSuffix(95, "不屈")
lbnametmpl:setSkillSuffix(96, "不屈")
lbnametmpl:setSkillSuffix(97, "不屈")
lbnametmpl:setSkillSuffix(98, "遗计")
lbnametmpl:setSkillSuffix(99, "遗计")
lbnametmpl:setSkillSuffix(100, "遗计")
lbnametmpl:setSkillSuffix(101, "遗计")
lbnametmpl:setSkillSuffix(102, "刚烈")
lbnametmpl:setSkillSuffix(103, "刚烈")
lbnametmpl:setSkillSuffix(104, "刚烈")
lbnametmpl:setSkillSuffix(105, "节命")
lbnametmpl:setSkillSuffix(106, "节命")
lbnametmpl:setSkillSuffix(107, "节命")
lbnametmpl:setSkillSuffix(108, "天义")
lbnametmpl:setSkillSuffix(109, "天义")
lbnametmpl:setSkillSuffix(110, "涅槃")
lbnametmpl:setSkillSuffix(111, "涅槃")
lbnametmpl:setSkillSuffix(112, "英魂")
lbnametmpl:setSkillSuffix(113, "断肠")
lbnametmpl:setSkillSuffix(114, "伤逝")
lbnametmpl:setSkillSuffix(115, "伤逝")
lbnametmpl:setSkillSuffix(116, "伤逝")
lbnametmpl:setSkillSuffix(117, "伤逝")
lbnametmpl:setSkillSuffix(118, "无言")
lbnametmpl:setSkillSuffix(119, "无言")
lbnametmpl:setSkillSuffix(120, "无言")
lbnametmpl:setSkillSuffix(121, "无言")
lbnametmpl:setSkillSuffix(122, "看破")
lbnametmpl:setSkillSuffix(123, "看破")
lbnametmpl:setSkillSuffix(124, "看破")
lbnametmpl:setSkillSuffix(125, "禁制")
lbnametmpl:setSkillSuffix(126, "禁制")
lbnametmpl:setSkillSuffix(127, "禁制")
lbnametmpl:setSkillSuffix(128, "毅重")
lbnametmpl:setSkillSuffix(129, "毅重")
lbnametmpl:setSkillSuffix(130, "乱舞")
lbnametmpl:setSkillSuffix(131, "乱舞")
lbnametmpl:setSkillSuffix(132, "鬼道")
lbnametmpl:setSkillSuffix(133, "鬼才")

