ALTER TABLE `login_states` ADD INDEX up_login_status (`server_id`, `player_id`, `login_time`);
ALTER TABLE `mailitem_histories` ADD INDEX up_mail_status (`server_id`, `mail_id`, `status`);
ALTER TABLE `mailitem_histories` ADD INDEX player_time (`player_id`, `receive_time`);
ALTER TABLE `topup_num` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `consume_gold` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `consume_gold` ADD INDEX server_player_item (`server_id`, `player_id`, `item_id`);
ALTER TABLE `consume_gold` ADD INDEX server_player_type (`server_id`, `player_id`, `consume_type`);
ALTER TABLE `consume_achievement` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `consume_achievement` ADD INDEX server_player_item (`server_id`, `player_id`, `item_id`);
ALTER TABLE `consume_achievement` ADD INDEX server_player_type (`server_id`, `player_id`, `consume_type`);
ALTER TABLE `consume_coin` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `consume_coin` ADD INDEX server_player_item (`server_id`, `player_id`, `item_id`);
ALTER TABLE `consume_coin` ADD INDEX server_player_type (`server_id`, `player_id`, `consume_type`);
ALTER TABLE `consume_tael` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `consume_tael` ADD INDEX server_player_item (`server_id`, `player_id`, `item_id`);
ALTER TABLE `consume_tael` ADD INDEX server_player_type (`server_id`, `player_id`, `consume_type`);
ALTER TABLE `consume_coupon` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `consume_coupon` ADD INDEX server_player_item (`server_id`, `player_id`, `item_id`);
ALTER TABLE `consume_coupon` ADD INDEX server_player_type (`server_id`, `player_id`, `consume_type`);
ALTER TABLE `item_courses` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `item_courses` ADD INDEX server_player_item (`server_id`, `player_id`, `item_id`);
ALTER TABLE `equip_courses` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `item_histories` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `item_histories` ADD INDEX server_player_item (`server_id`, `player_id`, `item_id`);
ALTER TABLE `enchant_histories` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `dungeon_statistics` ADD INDEX server_player (`server_id`, `player_id`);
ALTER TABLE `online_situations` ADD INDEX server(`server_id`);
ALTER TABLE `country_battle` ADD INDEX server(`server_id`);
